### ISSUE TITLE
List of the lacking features

### ISSUE THREAD

**Issue by kucukaslan** [MuhammedCanKucukaslan/cs-319-group1i-oops#69]
# Implementation
A list of the incomplete features
- [x] Disable enroll for the users not allowed in the campus. #85 
- [x] change password (profile page)
- [x] Registration page warnings. : @MuhammedCanKucukaslan  is working on it.
- [x] Diagnosis submission: #70 
- [x] Replace favicon with medical emoji via https://favicon.io/emoji-favicons/medical-symbol
- [x] HesCode validation:  #75 
- [x] Test Appointment @HikmetSimsir #89 
- [x] view coinstructors  #93 
- [x] User lastname #94 
- [x] constants.php file #95 
- [x] Forget password: @GirayAkyol #88 
- [x] usertype check's in pages, some pages seems to lack this? #94 
- [ ] lecture creation: #73 and #74 

## bug fixes
- [x] `composer update` in forthyhealth.duckdns.org
- [x] navbar fixes
- [x] delete debug `echo/print_r` statements 

# Presentation
## Final Presentation Slides
   - [x] Brief overview of innovative features
   - [x] Design pattern(s) that you used
   - [x] This part should be a Max of 6. minutes 
## Demo
   -  [x] Live demo of the software - 15 minutes
   -  [x] İş bölümü
# Report
-  [x] Demo Video: Think of this as a trailer of your software. Showcase your creativity. Maximum of 90 seconds
## Final Report (Dec 26 Midnight)
- [x] User Manual @MustafaYasirAltunhan 
- [x] Make sure you include step-by-step build instructions for your software. A third person that has the source code should be able to build your software @MuhammedCanKucukaslan 
- [x] Make sure include a 1-page description of the work allocation of your team. Use a bullet format to briefly describe the work done throughout the semester.

ps. You're free and allowed to extend this list, however this does not mean you're supposed to delete some code for the sake of extending the list.
